/**
 * Moments — data source.
 *
 * Reads from the static data/moments.json generated by `npm run sync`.
 * The Notion API is ONLY called during `npm run sync` (build-time).
 * No Notion calls happen at runtime.
 */

import { readFileSync } from 'fs';
import { join } from 'path';

export type Moment = {
  id: string;
  caption: string;
  date: string;
  image?: string;
  placeholderBg?: string;
  placeholderIcon?: string;
};

const DATA_FILE = join(process.cwd(), 'data', 'moments.json');

// ─── helpers ────────────────────────────────────────────────────────────────

const PLACEHOLDER_ICON_MAP: Record<number, string> = {
  0: 'coffee', 1: 'mountain', 2: 'headphones', 3: 'book', 4: 'camera',
  5: 'soup', 6: 'flower', 7: 'bike', 8: 'feather', 9: 'home',
};

const PLACEHOLDER_BG_MAP: Record<number, string> = {
  0: 'rgba(239, 159, 39, 0.18)', 1: 'rgba(29, 158, 117, 0.18)',
  2: 'rgba(127, 119, 221, 0.18)', 3: 'rgba(56, 138, 221, 0.18)',
  4: 'rgba(136, 135, 128, 0.20)', 5: 'rgba(216, 90, 48, 0.18)',
  6: 'rgba(212, 83, 126, 0.16)', 7: 'rgba(15, 142, 158, 0.18)',
  8: 'rgba(239, 159, 39, 0.15)', 9: 'rgba(56, 138, 221, 0.13)',
};

// ─── main fetch (runtime — reads static file only) ────────────────────────

/**
 * Returns all published moments, newest-first.
 * Zero Notion API calls — reads from the static JSON generated at build time.
 */
export async function getMoments(): Promise<Moment[]> {
  try {
    const raw = readFileSync(DATA_FILE, 'utf-8');
    const moments: Moment[] = JSON.parse(raw);

    return moments.map((m, i) => {
      if (m.image) return m;
      return {
        ...m,
        placeholderIcon: m.placeholderIcon ?? PLACEHOLDER_ICON_MAP[i % 10],
        placeholderBg: m.placeholderBg ?? PLACEHOLDER_BG_MAP[i % 10],
      };
    });
  } catch {
    return [];
  }
}

/** Latest N moments (for the home page grid). */
export async function getRecentMoments(n = 6): Promise<Moment[]> {
  const all = await getMoments();
  return all.slice(0, n);
}